package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 16 16:56:43 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAtelierViewImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public PAtelierViewImpl()
  {
  }
}
