package model.view;

import model.entity.PAuditeurImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 25 13:05:42 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAuditeur_CoordRowImpl
  extends ViewRowImpl {
    public static final int ENTITY_PAUDITEUR = 0;
    public static final int ENTITY_PCOORDONNEES = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
  public enum AttributesEnum
  {
        Admin {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getAdmin();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setAdmin((Integer)value);
            }
        }
        ,
        Candidatjuge {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getCandidatjuge();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setCandidatjuge((Timestamp)value);
            }
        }
        ,
        Codeauditeur {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getCodeauditeur();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setCodeauditeur((String)value);
            }
        }
        ,
        Juge {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getJuge();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setJuge((Timestamp)value);
            }
        }
        ,
        Motdepasse {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getMotdepasse();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setMotdepasse((String)value);
            }
        }
        ,
        Noauditeur {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getNoauditeur();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setNoauditeur((Integer)value);
            }
        }
        ,
        Nocoord {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getNocoord();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setNocoord((Integer)value);
            }
        }
        ,
        Nom {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getNom();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setNom((String)value);
            }
        }
        ,
        Prenom {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getPrenom();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setPrenom((String)value);
            }
        }
        ,
        Statut {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getStatut();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setStatut((String)value);
            }
        }
        ,
        Cell {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getCell();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setCell((String)value);
            }
        }
        ,
        CodePostal {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getCodePostal();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setCodePostal((String)value);
            }
        }
        ,
        Courriel {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getCourriel();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setCourriel((String)value);
            }
        }
        ,
        Nocoord1 {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getNocoord1();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setNocoord1((Integer)value);
            }
        }
        ,
        Noregion {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getNoregion();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setNoregion((Integer)value);
            }
        }
        ,
        Rue {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getRue();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setRue((String)value);
            }
        }
        ,
        Telephone {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getTelephone();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setTelephone((String)value);
            }
        }
        ,
        Ville {
            public Object get(PAuditeur_CoordRowImpl obj) {
                return obj.getVille();
            }

            public void put(PAuditeur_CoordRowImpl obj, Object value) {
                obj.setVille((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

    public abstract Object get(PAuditeur_CoordRowImpl object);

    public abstract void put(PAuditeur_CoordRowImpl object, Object value);

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


    public static final int ADMIN = AttributesEnum.Admin.index();
    public static final int CANDIDATJUGE = AttributesEnum.Candidatjuge.index();
    public static final int CODEAUDITEUR = AttributesEnum.Codeauditeur.index();
    public static final int JUGE = AttributesEnum.Juge.index();
    public static final int MOTDEPASSE = AttributesEnum.Motdepasse.index();
    public static final int NOAUDITEUR = AttributesEnum.Noauditeur.index();
    public static final int NOCOORD = AttributesEnum.Nocoord.index();
    public static final int NOM = AttributesEnum.Nom.index();
    public static final int PRENOM = AttributesEnum.Prenom.index();
    public static final int STATUT = AttributesEnum.Statut.index();
    public static final int CELL = AttributesEnum.Cell.index();
    public static final int CODEPOSTAL = AttributesEnum.CodePostal.index();
    public static final int COURRIEL = AttributesEnum.Courriel.index();
    public static final int NOCOORD1 = AttributesEnum.Nocoord1.index();
    public static final int NOREGION = AttributesEnum.Noregion.index();
    public static final int RUE = AttributesEnum.Rue.index();
    public static final int TELEPHONE = AttributesEnum.Telephone.index();
    public static final int VILLE = AttributesEnum.Ville.index();

    /**
     * This is the default constructor (do not remove).
     */
  public PAuditeur_CoordRowImpl()
  {
  }

  /**
   * Gets PAuditeur entity object.
   * @return the PAuditeur
   */
  public PAuditeurImpl getPAuditeur()
  {
    return (PAuditeurImpl) getEntity(ENTITY_PAUDITEUR);
  }

  /**
   * Gets PCoordonnees entity object.
   * @return the PCoordonnees
   */
  public EntityImpl getPCoordonnees()
  {
    return (EntityImpl) getEntity(ENTITY_PCOORDONNEES);
  }

  /**
   * Gets the attribute value for ADMIN using the alias name Admin.
   * @return the ADMIN
   */
  public Integer getAdmin()
  {
    return (Integer) getAttributeInternal(ADMIN);
  }

  /**
   * Sets <code>value</code> as attribute value for ADMIN using the alias name Admin.
   * @param value value to set the ADMIN
   */
  public void setAdmin(Integer value)
  {
    setAttributeInternal(ADMIN, value);
  }

  /**
   * Gets the attribute value for CANDIDATJUGE using the alias name Candidatjuge.
   * @return the CANDIDATJUGE
   */
  public Timestamp getCandidatjuge()
  {
    return (Timestamp) getAttributeInternal(CANDIDATJUGE);
  }

  /**
   * Sets <code>value</code> as attribute value for CANDIDATJUGE using the alias name Candidatjuge.
   * @param value value to set the CANDIDATJUGE
   */
  public void setCandidatjuge(Timestamp value)
  {
    setAttributeInternal(CANDIDATJUGE, value);
  }

  /**
   * Gets the attribute value for CODEAUDITEUR using the alias name Codeauditeur.
   * @return the CODEAUDITEUR
   */
  public String getCodeauditeur()
  {
    return (String) getAttributeInternal(CODEAUDITEUR);
  }

  /**
   * Sets <code>value</code> as attribute value for CODEAUDITEUR using the alias name Codeauditeur.
   * @param value value to set the CODEAUDITEUR
   */
  public void setCodeauditeur(String value)
  {
    setAttributeInternal(CODEAUDITEUR, value);
  }

  /**
   * Gets the attribute value for JUGE using the alias name Juge.
   * @return the JUGE
   */
  public Timestamp getJuge()
  {
    return (Timestamp) getAttributeInternal(JUGE);
  }

  /**
   * Sets <code>value</code> as attribute value for JUGE using the alias name Juge.
   * @param value value to set the JUGE
   */
  public void setJuge(Timestamp value)
  {
    setAttributeInternal(JUGE, value);
  }

  /**
   * Gets the attribute value for MOTDEPASSE using the alias name Motdepasse.
   * @return the MOTDEPASSE
   */
  public String getMotdepasse()
  {
    return (String) getAttributeInternal(MOTDEPASSE);
  }

  /**
   * Sets <code>value</code> as attribute value for MOTDEPASSE using the alias name Motdepasse.
   * @param value value to set the MOTDEPASSE
   */
  public void setMotdepasse(String value)
  {
    setAttributeInternal(MOTDEPASSE, value);
  }

  /**
   * Gets the attribute value for NOAUDITEUR using the alias name Noauditeur.
   * @return the NOAUDITEUR
   */
  public Integer getNoauditeur()
  {
    return (Integer) getAttributeInternal(NOAUDITEUR);
  }

  /**
   * Sets <code>value</code> as attribute value for NOAUDITEUR using the alias name Noauditeur.
   * @param value value to set the NOAUDITEUR
   */
  public void setNoauditeur(Integer value)
  {
    setAttributeInternal(NOAUDITEUR, value);
  }

  /**
   * Gets the attribute value for NOCOORD using the alias name Nocoord.
   * @return the NOCOORD
   */
  public Integer getNocoord()
  {
    return (Integer) getAttributeInternal(NOCOORD);
  }

  /**
   * Sets <code>value</code> as attribute value for NOCOORD using the alias name Nocoord.
   * @param value value to set the NOCOORD
   */
  public void setNocoord(Integer value)
  {
    setAttributeInternal(NOCOORD, value);
  }

  /**
   * Gets the attribute value for NOM using the alias name Nom.
   * @return the NOM
   */
  public String getNom()
  {
    return (String) getAttributeInternal(NOM);
  }

  /**
   * Sets <code>value</code> as attribute value for NOM using the alias name Nom.
   * @param value value to set the NOM
   */
  public void setNom(String value)
  {
    setAttributeInternal(NOM, value);
  }

  /**
   * Gets the attribute value for PRENOM using the alias name Prenom.
   * @return the PRENOM
   */
  public String getPrenom()
  {
    return (String) getAttributeInternal(PRENOM);
  }

  /**
   * Sets <code>value</code> as attribute value for PRENOM using the alias name Prenom.
   * @param value value to set the PRENOM
   */
  public void setPrenom(String value)
  {
    setAttributeInternal(PRENOM, value);
  }

  /**
   * Gets the attribute value for STATUT using the alias name Statut.
   * @return the STATUT
   */
  public String getStatut()
  {
    return (String) getAttributeInternal(STATUT);
  }

  /**
   * Sets <code>value</code> as attribute value for STATUT using the alias name Statut.
   * @param value value to set the STATUT
   */
  public void setStatut(String value)
  {
    setAttributeInternal(STATUT, value);
  }

  /**
   * Gets the attribute value for CELL using the alias name Cell.
   * @return the CELL
   */
  public String getCell()
  {
    return (String) getAttributeInternal(CELL);
  }

  /**
   * Sets <code>value</code> as attribute value for CELL using the alias name Cell.
   * @param value value to set the CELL
   */
  public void setCell(String value)
  {
    setAttributeInternal(CELL, value);
  }

  /**
   * Gets the attribute value for CODE_POSTAL using the alias name CodePostal.
   * @return the CODE_POSTAL
   */
  public String getCodePostal()
  {
    return (String) getAttributeInternal(CODEPOSTAL);
  }

  /**
   * Sets <code>value</code> as attribute value for CODE_POSTAL using the alias name CodePostal.
   * @param value value to set the CODE_POSTAL
   */
  public void setCodePostal(String value)
  {
    setAttributeInternal(CODEPOSTAL, value);
  }

  /**
   * Gets the attribute value for COURRIEL using the alias name Courriel.
   * @return the COURRIEL
   */
  public String getCourriel()
  {
    return (String) getAttributeInternal(COURRIEL);
  }

  /**
   * Sets <code>value</code> as attribute value for COURRIEL using the alias name Courriel.
   * @param value value to set the COURRIEL
   */
  public void setCourriel(String value)
  {
    setAttributeInternal(COURRIEL, value);
  }

  /**
   * Gets the attribute value for NOCOORD using the alias name Nocoord1.
   * @return the NOCOORD
   */
  public Integer getNocoord1()
  {
    return (Integer) getAttributeInternal(NOCOORD1);
  }

  /**
   * Sets <code>value</code> as attribute value for NOCOORD using the alias name Nocoord1.
   * @param value value to set the NOCOORD
   */
  public void setNocoord1(Integer value)
  {
    setAttributeInternal(NOCOORD1, value);
  }

  /**
   * Gets the attribute value for NOREGION using the alias name Noregion.
   * @return the NOREGION
   */
  public Integer getNoregion()
  {
    return (Integer) getAttributeInternal(NOREGION);
  }

  /**
   * Sets <code>value</code> as attribute value for NOREGION using the alias name Noregion.
   * @param value value to set the NOREGION
   */
  public void setNoregion(Integer value)
  {
    setAttributeInternal(NOREGION, value);
  }

  /**
   * Gets the attribute value for RUE using the alias name Rue.
   * @return the RUE
   */
  public String getRue()
  {
    return (String) getAttributeInternal(RUE);
  }

  /**
   * Sets <code>value</code> as attribute value for RUE using the alias name Rue.
   * @param value value to set the RUE
   */
  public void setRue(String value)
  {
    setAttributeInternal(RUE, value);
  }

  /**
   * Gets the attribute value for TELEPHONE using the alias name Telephone.
   * @return the TELEPHONE
   */
  public String getTelephone()
  {
    return (String) getAttributeInternal(TELEPHONE);
  }

  /**
   * Sets <code>value</code> as attribute value for TELEPHONE using the alias name Telephone.
   * @param value value to set the TELEPHONE
   */
  public void setTelephone(String value)
  {
    setAttributeInternal(TELEPHONE, value);
  }

  /**
   * Gets the attribute value for VILLE using the alias name Ville.
   * @return the VILLE
   */
  public String getVille()
  {
    return (String) getAttributeInternal(VILLE);
  }

  /**
   * Sets <code>value</code> as attribute value for VILLE using the alias name Ville.
   * @param value value to set the VILLE
   */
  public void setVille(String value)
  {
    setAttributeInternal(VILLE, value);
  }

/*
    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
 /*/** protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef)
    throws Exception
  {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }
*/
 /* /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
 /* protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef)
    throws Exception
  {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }*/
}
