package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 02 13:37:31 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAuditeurImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public PAuditeurImpl()
  {
  }
}
