REM -- APP tablespace

CREATE TABLE CATEGORIES(
	ID 			NUMBER(7) NOT NULL,
	NOM 		VARCHAR2(50) NOT NULL,
	CONSTRAINT CATID PRIMARY KEY (ID)
) TABLESPACE ACME_APP;

CREATE TABLE PRODUITS(
	ID			NUMBER(8),
	IDCATEGORIE NUMBER(8),
	NOM			VARCHAR2(150),
	CONSTRAINT PRODUITSID PRIMARY KEY (ID),
	CONSTRAINT PRODUITSCATID FOREIGN KEY (IDCATEGORIE) REFERENCES CATEGORIES(ID)
) TABLESPACE ACME_APP;

REM -- ADMIN tablespace

CREATE TABLE CLIENTS(
	ID			NUMBER(8),
	NOM 		VARCHAR2(50) NOT NULL,
	CONSTRAINT CLIENTSID PRIMARY KEY (ID)
) TABLESPACE ACME_ADMIN;

CREATE TABLE BACKUPLOGS(
	ID			NUMBER(8),
	LOG_DATE 	DATE NOT NULL,
	CONSTRAINT BLOGSID PRIMARY KEY (ID)
) TABLESPACE ACME_ADMIN;



COMMIT;