
PROMPT Page 2 #1 Les différentes versions pour la colonne &1
SELECT VERSIONS_OPERATION, &1
FROM &2 VERSIONS BETWEEN TIMESTAMP (SYSTIMESTAMP - INTERVAL '&3' SECOND)
AND SYSTIMESTAMP
WHERE &4;

PROMPT Page 3 #2
FLASHBACK TABLE &1 TO TIMESTAMP (SYSTIMESTAMP - INTERVAL '&2' SECOND)

PROMPT Page 3 #3
PROMPT 1)
	CREATE TABLE PRODUCT (No INT, nom VARCHAR2(100));
PROMPT 2)
	DROP TABLE PRODUCT;
PROMPT 3)
	FLASHBACK TABLE PRODUCT TO BEFORE DROP;