CREATE TABLESPACE inventaire 
DATAFILE 'INV1.DBF' SIZE 2M AUTOEXTEND OFF, 
		 'INV2.DBF' SIZE 2M AUTOEXTEND ON NEXT 1M MAXSIZE 10M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

// AFFICHAGE : 
SELECT ts#, bytes/1024 "Ko", status, substr(name,0,35) FROM v$datafile;