package model.view.lecture;

import model.view.lecture.common.Seq_coordRow;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 25 14:02:46 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Seq_coordRowImpl
  extends ViewRowImpl
  implements Seq_coordRow
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum
  {
    SeqNocoord
    {
      public Object get(Seq_coordRowImpl obj)
      {
        return obj.getSeqNocoord();
      }

      public void put(Seq_coordRowImpl obj, Object value)
      {
        obj.setSeqNocoord((Integer)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(Seq_coordRowImpl object);

    public abstract void put(Seq_coordRowImpl object, Object value);

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int SEQNOCOORD = AttributesEnum.SeqNocoord.index();

  /**
   * This is the default constructor (do not remove).
   */
  public Seq_coordRowImpl()
  {
  }

  /**
   * Gets the attribute value for the calculated attribute SeqNocoord.
   * @return the SeqNocoord
   */
  public Integer getSeqNocoord()
  {
    return (Integer) getAttributeInternal(SEQNOCOORD);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute SeqNocoord.
   * @param value value to set the  SeqNocoord
   */
  public void setSeqNocoord(Integer value)
  {
    setAttributeInternal(SEQNOCOORD, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef)
    throws Exception
  {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
    {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
