package model.view.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 07 16:24:29 EDT 2013
// ---------------------------------------------------------------------
public interface PInscriptionViewRow
  extends Row
{
  Integer getNoauditeur();

  void setNoauditeur(Integer value);

  Integer getNoatel();

  void setNoatel(Integer value);

  Timestamp getDateinscription();

  void setDateinscription(Timestamp value);

  String getModePaiement();

  void setModePaiement(String value);

  String getNoCarte();

  void setNoCarte(String value);

  Integer getNoCheque();

  void setNoCheque(Integer value);

  Timestamp getDateExpire();

  void setDateExpire(Timestamp value);

  Integer getAcquitter();

  void setAcquitter(Integer value);

  Integer getConfirmationenvoyee();

  void setConfirmationenvoyee(Integer value);

  String getCreepar();

  void setCreepar(String value);
}
