package model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 02 13:11:02 EDT 2013
// ---------------------------------------------------------------------
public interface PAuditeurLogIn
  extends ViewObject
{
  int auditeurConnecte(String paramCode, String paramMotDePasse);

}
