package model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 07 17:03:05 EDT 2013
// ---------------------------------------------------------------------
public interface PAuditeurLogInRow
  extends Row
{
  boolean verifierMDP(String mdp);

  void nouveauMDP(String value);
}
