package model.view.client;

import model.view.common.PAuditeurLogInRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 07 17:03:05 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAuditeurLogInRowClient
  extends RowImpl
  implements PAuditeurLogInRow
{
  /**
   * This is the default constructor (do not remove).
   */
  public PAuditeurLogInRowClient()
  {
  }


  public void nouveauMDP(String value)
  {
    Object _ret =
      getApplicationModuleProxy().riInvokeExportedMethod(this,"nouveauMDP",new String [] {"java.lang.String"},new Object[] {value});
    return;
  }

  public boolean verifierMDP(String mdp)
  {
    Object _ret =
      getApplicationModuleProxy().riInvokeExportedMethod(this,"verifierMDP",new String [] {"java.lang.String"},new Object[] {mdp});
    return ((Boolean)_ret).booleanValue();
  }
}
