package model.view.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 07 16:24:29 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PInscriptionViewRowClient
  extends RowImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public PInscriptionViewRowClient()
  {
  }

  public Integer getNoauditeur()
  {
    return (Integer) getAttribute("Noauditeur");
  }

  public void setNoauditeur(Integer value)
  {
    setAttribute("Noauditeur", value);
  }

  public Integer getNoatel()
  {
    return (Integer) getAttribute("Noatel");
  }

  public void setNoatel(Integer value)
  {
    setAttribute("Noatel", value);
  }

  public Timestamp getDateinscription()
  {
    return (Timestamp) getAttribute("Dateinscription");
  }

  public void setDateinscription(Timestamp value)
  {
    setAttribute("Dateinscription", value);
  }

  public String getModePaiement()
  {
    return (String) getAttribute("ModePaiement");
  }

  public void setModePaiement(String value)
  {
    setAttribute("ModePaiement", value);
  }

  public String getNoCarte()
  {
    return (String) getAttribute("NoCarte");
  }

  public void setNoCarte(String value)
  {
    setAttribute("NoCarte", value);
  }

  public Integer getNoCheque()
  {
    return (Integer) getAttribute("NoCheque");
  }

  public void setNoCheque(Integer value)
  {
    setAttribute("NoCheque", value);
  }

  public Timestamp getDateExpire()
  {
    return (Timestamp) getAttribute("DateExpire");
  }

  public void setDateExpire(Timestamp value)
  {
    setAttribute("DateExpire", value);
  }

  public Integer getAcquitter()
  {
    return (Integer) getAttribute("Acquitter");
  }

  public void setAcquitter(Integer value)
  {
    setAttribute("Acquitter", value);
  }

  public Integer getConfirmationenvoyee()
  {
    return (Integer) getAttribute("Confirmationenvoyee");
  }

  public void setConfirmationenvoyee(Integer value)
  {
    setAttribute("Confirmationenvoyee", value);
  }

  public String getCreepar()
  {
    return (String) getAttribute("Creepar");
  }

  public void setCreepar(String value)
  {
    setAttribute("Creepar", value);
  }
}
