package model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 02 14:38:33 EDT 2013
// ---------------------------------------------------------------------
public interface PAuditeurViewRow
  extends Row
{
  void rentrerMDP(String value);
}
