package model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 02 13:38:05 EDT 2013
// ---------------------------------------------------------------------
public interface PAuditeurRow
  extends Row
{
  void soumettreCandi();

  void annulerCandi();

  void annulerJuge();
}
