PROMPT create table 'EA_ATELIERS'
CREATE TABLE EA_ATELIERS 
(
  ID_ATELIER NUMBER NOT NULL 
, LANGUE VARCHAR2(20) NOT NULL 
, NOM_ATELIER VARCHAR2(20) NOT NULL 
, ID_JURY NUMBER NOT NULL 
, ID_TYPE NUMBER NOT NULL 
, ID_CATEGORIE NUMBER NOT NULL 
, CONSTRAINT P_ATELIERS_PK PRIMARY KEY 
  (
    ID_ATELIER 
  )
  ENABLE 
);

PROMPT create table 'EA_AUDITEURS'
CREATE TABLE EA_AUDITEURS 
(
  ID_AUDITEUR NUMBER NOT NULL 
, CAT_AGE VARCHAR2(20) 
, NOM VARCHAR2(20) 
, ID_JURY NUMBER NOT NULL 
, CONSTRAINT P_AUDITEURS_PK PRIMARY KEY 
  (
    ID_AUDITEUR 
  )
  ENABLE 
);

PROMPT create table 'EA_CATEGORIE_ATELIER'
CREATE TABLE EA_CATEGORIE_ATELIER 
(
  ID_CATEGORIE NUMBER NOT NULL 
, CONSTRAINT P_CATEGORIES_PK PRIMARY KEY 
  (
    ID_CATEGORIE 
  )
  ENABLE 
);

PROMPT create table 'EA_CRITERES'
CREATE TABLE EA_CRITERES 
(
  C1 VARCHAR2(20) 
, C2 VARCHAR2(20) 
, C3 VARCHAR2(20) 
, C4 VARCHAR2(20) 
, C5 VARCHAR2(20) 
, ID_ATELIER NUMBER NOT NULL 
);

PROMPT create table 'EA_ECOLES'
CREATE TABLE EA_ECOLES 
(
  ID_ECOLE NUMBER NOT NULL 
, NOM_EXPO VARCHAR2(50) NOT NULL 
, NOM VARCHAR2(20) 
, CONSTRAINT P_ECOLES_PK PRIMARY KEY 
  (
    ID_ECOLE 
  )
  ENABLE 
);

PROMPT create table 'EA_EXPOSANTS'
CREATE TABLE EA_EXPOSANTS 
(
  ID_EXPOSANT NUMBER NOT NULL 
, NOM VARCHAR2(20) 
, ID_ATELIER NUMBER NOT NULL 
, ID_ECOLE NUMBER NOT NULL 
, CONSTRAINT P_EXPOSANTS_PK PRIMARY KEY 
  (
    ID_EXPOSANT 
  )
  ENABLE 
);

PROMPT create table 'EA_EXPOSITIONS'
CREATE TABLE EA_EXPOSITIONS 
(
  NOM_EXPO VARCHAR2(50) NOT NULL 
, DATE_EXPO DATE 
, LIEU_EXPO VARCHAR2(20) 
, ID_ECOLE NUMBER NOT NULL 
, CONSTRAINT P_EXPOSITIONS_PK PRIMARY KEY 
  (
    NOM_EXPO 
  )
  ENABLE 
);

PROMPT create table 'EA_INSCRIPTION'
CREATE TABLE EA_INSCRIPTION 
(
  ID_AUDITEUR NUMBER NOT NULL 
, ID_ATELIER NUMBER NOT NULL 
);

PROMPT create table 'EA_JURY'
CREATE TABLE EA_JURY 
(
  ID_JURY NUMBER NOT NULL 
, CONSTRAINT P_JURY_PK PRIMARY KEY 
  (
    ID_JURY 
  )
  ENABLE 
);

PROMPT create table 'EA_TYPE_ATELIER'
CREATE TABLE EA_TYPE_ATELIER 
(
  ID_TYPE NUMBER NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID_TYPE 
  )
  ENABLE 
);

PROMPT alter table 'EA_ATELIERS'
ALTER TABLE EA_ATELIERS
ADD CONSTRAINT P_ATELIERS_FK FOREIGN KEY
(
  ID_CATEGORIE 
)
REFERENCES EA_CATEGORIE_ATELIER
(
  ID_CATEGORIE 
)
ENABLE;

PROMPT alter table 'EA_ATELIERS'
ALTER TABLE EA_ATELIERS
ADD CONSTRAINT P_ATELIERS_P_JURY_FK FOREIGN KEY
(
  ID_JURY 
)
REFERENCES EA_JURY
(
  ID_JURY 
)
ENABLE;

PROMPT alter table 'EA_ATELIERS'
ALTER TABLE EA_ATELIERS
ADD CONSTRAINT P_ATELIERS_P_TYPE_ATELIER_FK FOREIGN KEY
(
  ID_TYPE 
)
REFERENCES EA_TYPE_ATELIER
(
  ID_TYPE 
)
ENABLE;

PROMPT alter table 'EA_AUDITEURS'
ALTER TABLE EA_AUDITEURS
ADD CONSTRAINT P_AUDITEURS_P_JURY_FK FOREIGN KEY
(
  ID_JURY 
)
REFERENCES EA_JURY
(
  ID_JURY 
)
ENABLE;

PROMPT alter table 'EA_CRITERES'
ALTER TABLE EA_CRITERES
ADD CONSTRAINT P_CRITERES_P_ATELIERS_FK FOREIGN KEY
(
  ID_ATELIER 
)
REFERENCES EA_ATELIERS
(
  ID_ATELIER 
)
ENABLE;

PROMPT alter table 'EA_ECOLES'
ALTER TABLE EA_ECOLES
ADD CONSTRAINT P_ECOLES_P_EXPOSITIONS_FK FOREIGN KEY
(
  NOM_EXPO 
)
REFERENCES EA_EXPOSITIONS
(
  NOM_EXPO 
)
ENABLE;

PROMPT alter table 'EA_EXPOSANTS'
ALTER TABLE EA_EXPOSANTS
ADD CONSTRAINT P_EXPOSANTS_P_ATELIERS_FK FOREIGN KEY
(
  ID_ATELIER 
)
REFERENCES EA_ATELIERS
(
  ID_ATELIER 
)
ENABLE;

PROMPT alter table 'EA_EXPOSANTS'
ALTER TABLE EA_EXPOSANTS
ADD CONSTRAINT P_EXPOSANTS_P_ECOLES_FK FOREIGN KEY
(
  ID_ECOLE 
)
REFERENCES EA_ECOLES
(
  ID_ECOLE 
)
ENABLE;

PROMPT alter table 'EA_EXPOSITIONS'
ALTER TABLE EA_EXPOSITIONS
ADD CONSTRAINT P_EXPOSITIONS_P_ECOLES_FK FOREIGN KEY
(
  ID_ECOLE 
)
REFERENCES EA_ECOLES
(
  ID_ECOLE 
)
ENABLE;

PROMPT alter table 'EA_INSCRIPTION'
ALTER TABLE EA_INSCRIPTION
ADD CONSTRAINT P_INSCRIPTION_P_ATELIERS_FK FOREIGN KEY
(
  ID_ATELIER 
)
REFERENCES EA_ATELIERS
(
  ID_ATELIER 
)
ENABLE;

PROMPT alter table 'EA_INSCRIPTION'
ALTER TABLE EA_INSCRIPTION
ADD CONSTRAINT P_INSCRIPTION_P_AUDITEURS_FK FOREIGN KEY
(
  ID_AUDITEUR 
)
REFERENCES EA_AUDITEURS
(
  ID_AUDITEUR 
)
ENABLE;

PROMPT create sequence 'EA_ATELIERS_SEQ'
CREATE SEQUENCE EA_ATELIERS_SEQ;

PROMPT create sequence 'EA_AUDITEURS_SEQ'
CREATE SEQUENCE EA_AUDITEURS_SEQ;

PROMPT create sequence 'EA_CATEGORIE_ATELIER_SEQ'
CREATE SEQUENCE EA_CATEGORIE_ATELIER_SEQ;

PROMPT create sequence 'EA_CRITERES_SEQ'
CREATE SEQUENCE EA_CRITERES_SEQ;

PROMPT create sequence 'EA_ECOLES_SEQ'
CREATE SEQUENCE EA_ECOLES_SEQ;

PROMPT create sequence 'EA_EXPOSANTS_SEQ'
CREATE SEQUENCE EA_EXPOSANTS_SEQ;

PROMPT create sequence 'EA_EXPOSITIONS_SEQ'
CREATE SEQUENCE EA_EXPOSITIONS_SEQ;

PROMPT create sequence 'EA_INSCRIPTION_SEQ'
CREATE SEQUENCE EA_INSCRIPTION_SEQ;

PROMPT create sequence 'EA_JURY_SEQ'
CREATE SEQUENCE EA_JURY_SEQ;

PROMPT create sequence 'EA_TYPE_ATELIER_SEQ'
CREATE SEQUENCE EA_TYPE_ATELIER_SEQ;

PROMPT create trigger 'EA_ATELIERS_TRG'
CREATE TRIGGER EA_ATELIERS_TRG 
BEFORE INSERT ON EA_ATELIERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_ATELIER IS NULL THEN
      SELECT EA_ATELIERS_SEQ.NEXTVAL INTO :NEW.ID_ATELIER FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

PROMPT create trigger 'EA_AUDITEURS_TRG'
CREATE TRIGGER EA_AUDITEURS_TRG 
BEFORE INSERT ON EA_AUDITEURS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_AUDITEUR IS NULL THEN
      SELECT EA_AUDITEURS_SEQ.NEXTVAL INTO :NEW.ID_AUDITEUR FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

PROMPT create trigger 'EA_CATEGORIE_ATELIER_TRG'
CREATE TRIGGER EA_CATEGORIE_ATELIER_TRG 
BEFORE INSERT ON EA_CATEGORIE_ATELIER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_CATEGORIE IS NULL THEN
      SELECT EA_CATEGORIE_ATELIER_SEQ.NEXTVAL INTO :NEW.ID_CATEGORIE FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

PROMPT create trigger 'EA_CRITERES_TRG'
CREATE TRIGGER EA_CRITERES_TRG 
BEFORE INSERT ON EA_CRITERES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.C1 IS NULL THEN
      SELECT EA_CRITERES_SEQ.NEXTVAL INTO :NEW.C1 FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

PROMPT create trigger 'EA_ECOLES_TRG'
CREATE TRIGGER EA_ECOLES_TRG 
BEFORE INSERT ON EA_ECOLES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_ECOLE IS NULL THEN
      SELECT EA_ECOLES_SEQ.NEXTVAL INTO :NEW.ID_ECOLE FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

PROMPT create trigger 'EA_EXPOSANTS_TRG'
CREATE TRIGGER EA_EXPOSANTS_TRG 
BEFORE INSERT ON EA_EXPOSANTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_EXPOSANT IS NULL THEN
      SELECT EA_EXPOSANTS_SEQ.NEXTVAL INTO :NEW.ID_EXPOSANT FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

PROMPT create trigger 'EA_EXPOSITIONS_TRG'
CREATE TRIGGER EA_EXPOSITIONS_TRG 
BEFORE INSERT ON EA_EXPOSITIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.NOM_EXPO IS NULL THEN
      SELECT EA_EXPOSITIONS_SEQ.NEXTVAL INTO :NEW.NOM_EXPO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

PROMPT create trigger 'EA_INSCRIPTION_TRG'
CREATE TRIGGER EA_INSCRIPTION_TRG 
BEFORE INSERT ON EA_INSCRIPTION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_AUDITEUR IS NULL THEN
      SELECT EA_INSCRIPTION_SEQ.NEXTVAL INTO :NEW.ID_AUDITEUR FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

PROMPT create trigger 'EA_JURY_TRG'
CREATE TRIGGER EA_JURY_TRG 
BEFORE INSERT ON EA_JURY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_JURY IS NULL THEN
      SELECT EA_JURY_SEQ.NEXTVAL INTO :NEW.ID_JURY FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

PROMPT create trigger 'EA_TYPE_ATELIER_TRG'
CREATE TRIGGER EA_TYPE_ATELIER_TRG 
BEFORE INSERT ON EA_TYPE_ATELIER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_TYPE IS NULL THEN
      SELECT EA_TYPE_ATELIER_SEQ.NEXTVAL INTO :NEW.ID_TYPE FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
