package model.view.lecture.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 25 14:02:46 EDT 2013
// ---------------------------------------------------------------------
public interface Seq_coordRow
  extends Row
{
  Integer getSeqNocoord();

  void setSeqNocoord(Integer value);
}
