CREATE TRIGGER EA_EXPOSITIONS_TRG 
BEFORE INSERT ON EA_EXPOSITIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.NOM_EXPO IS NULL THEN
      SELECT EA_EXPOSITIONS_SEQ.NEXTVAL INTO :NEW.NOM_EXPO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
