package model.view.client;

import model.view.common.PAuditeurRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 02 13:38:05 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAuditeurRowClient
  extends RowImpl
  implements PAuditeurRow
{
  /**
   * This is the default constructor (do not remove).
   */
  public PAuditeurRowClient()
  {
  }

  public void annulerCandi()
  {
    Object _ret =
      getApplicationModuleProxy().riInvokeExportedMethod(this,"annulerCandi",null,null);
    return;
  }

  public void annulerJuge()
  {
    Object _ret =
      getApplicationModuleProxy().riInvokeExportedMethod(this,"annulerJuge",null,null);
    return;
  }

  public void soumettreCandi()
  {
    Object _ret =
      getApplicationModuleProxy().riInvokeExportedMethod(this,"soumettreCandi",null,null);
    return;
  }
}
